services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    image: simple-lms
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=lms_db
      - POSTGRES_USER=user_lms
      - POSTGRES_PASSWORD=pass_lms
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: